version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database_historical.sql:/docker-entrypoint-initdb.d/database_historical.sql
    ports:
      - "3306:3306"
