version: '3.3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'Historical_Data'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - my-db:/var/lib/mysql

volumes:
  my-db:
